export const SEND_OPERATION_OTP = 'SEND_OPERATION_OTP';
export const EVALUATED_OPERATION_OTP = 'EVALUATED_OPERATION_OTP';
export const EVALUATED_OPERATION_OTP_RESULT = 'EVALUATED_OPERATION_OTP_RESULT';
